apiVersion: v1
kind: Namespace
metadata:
  name: epictetus
  labels:
    name: epictetus
    app: epictetus

---
apiVersion: v1
kind: Secret
metadata:
  name: epictetus-secrets
  namespace: epictetus
  labels:
    app: epictetus
type: Opaque
data:
  # Base64 encoded values - replace these with your actual values
  # echo -n "your-cloudflare-api-token" | base64
  cloudflare-api-token: "eW91ci1jbG91ZGZsYXJlLWFwaS10b2tlbg=="
